# Site settings
title: Jen Myers
email: hello@jenmyers.net

# Paths
baseurl: ""
url: "https://jenmyers.net"
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
permalink: none

# Post settings
future: false
excerpt_separator: <!--more-->
