# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jen Myers
email: hello@jenmyers.net
description: Personal website of technologist and writer Jen Myers.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jenmyers.net" # the base hostname & protocol for your site, e.g. http://example.com
sass:
  sass_dir: _sass

twitter_username: antiheroine

# Build settings
permalink: none

# Post settings
future: false
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
