# Site settings

title: Jen Myers
email: hello@jenmyers.net
description: Personal website of technologist and writer Jen Myers.

baseurl: ""
url: "https://jenmyers.net"
sass:
  sass_dir: _sass

twitter_username: antiheroine

# Build settings
permalink: none

# Post settings
future: false
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-redirect-from

# Tools
- name: Image Optimizer
  uses: crush-pics/crush-pics-github-action@v1.0

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
